
name: Deploy for Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deployLambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "us-east-1"
    
    - name: Zip js files
      run: |
          echo "************** Result of ls -al **************"
          ls -al
          echo "************** Result of zip **************"
          zip index.js.zip index.js
          echo "************** Result of ls **************"
          ls -al
    
    - name: deploy lambda
      run: |
          aws lambda update-function-code --function-name webapp-lambda --zip-file=fileb://index.js.zip